language: android
sudo: false
android:
  components:
  - build-tools-25.0.0
  - android-25
  - extra-android-support
  - extra-android-m2repository
script:
- ./gradlew build
- cd ./lib/build/outputs/aar
- mv lib-debug.aar hiupgrate.aar
- git init
- git config user.name "${U_NAME}"
- git config user.email "${U_EMAIL}"
- git add hiupgrate.aar
- git commit -m "Update tools"
- git push --force "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
